version: '3.8'
services:
  mysql:
    image: mysql:8
    container_name: mysql_library
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: library
    ports:
      - "3306:3306"
    volumes:
      - ./schema.sql:/docker-entrypoint-initdb.d/1_schema.sql
      - ./data.sql:/docker-entrypoint-initdb.d/2_data.sql
